FROM node:12-slim as Build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

ENV NODE_ENV=production

RUN npm ci --production && npm clean cache --force

COPY . .

ENTRYPOINT ["node", "index.js"]
